Revert "Revert "config: yoshino: Disable CONFIG_CC_STACKPROTECTOR_STRONG""
This reverts commit 15be1304ba04fc0d903bfe2a1a45ed3dbb82a34f.

Error: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler.

Signed-off-by: ariffjenong <arifbuditantodablekk@gmail.com>